// <auto-generated />
using System;
using DroneMesh3D.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DroneMesh3D.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613210748_AddAreaName")]
    partial class AddAreaName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DroneMesh3D.Core.Entities.AreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Polygon, 4326)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SequentialNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("DroneMesh3D.Core.Entities.FlightPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<double>("CoveredAreaM2")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("EstimatedFlightTimeS")
                        .HasColumnType("double precision");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer");

                    b.Property<double>("TotalDistanceM")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("FlightPlans");
                });

            modelBuilder.Entity("DroneMesh3D.Core.Entities.FlightPlanEntity", b =>
                {
                    b.HasOne("DroneMesh3D.Core.Entities.AreaEntity", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DroneMesh3D.Core.FlightPath.GridModeParameters", "GridParameters", b1 =>
                        {
                            b1.Property<Guid>("FlightPlanEntityId")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("AltitudeM");

                            b1.Property<double>("FrontOverlapPercent");

                            b1.Property<double?>("HeadingDegrees");

                            b1.Property<double>("SideOverlapPercent");

                            b1.HasKey("FlightPlanEntityId");

                            b1.ToTable("FlightPlans");

                            b1.ToJson("GridParameters");

                            b1.WithOwner()
                                .HasForeignKey("FlightPlanEntityId");

                            b1.OwnsOne("DroneMesh3D.Core.FlightPath.CameraParameters", "Camera", b2 =>
                                {
                                    b2.Property<Guid>("GridModeParametersFlightPlanEntityId");

                                    b2.Property<double>("FocalLengthMm");

                                    b2.Property<int>("ImageHeightPx");

                                    b2.Property<int>("ImageWidthPx");

                                    b2.Property<double>("SensorWidthMm");

                                    b2.HasKey("GridModeParametersFlightPlanEntityId");

                                    b2.ToTable("FlightPlans");

                                    b2.WithOwner()
                                        .HasForeignKey("GridModeParametersFlightPlanEntityId");
                                });

                            b1.Navigation("Camera")
                                .IsRequired();
                        });

                    b.OwnsOne("DroneMesh3D.Core.FlightPath.PoiModeParameters", "PoiParameters", b1 =>
                        {
                            b1.Property<Guid>("FlightPlanEntityId")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("AltitudeM");

                            b1.Property<double?>("CameraHorizontalFovDegrees");

                            b1.Property<double>("CenterLatitude");

                            b1.Property<double>("CenterLongitude");

                            b1.Property<double>("GimbalPitchDegrees");

                            b1.Property<int?>("OrbitShape");

                            b1.Property<double?>("OverlapPercent");

                            b1.Property<int?>("PhotoCount");

                            b1.Property<double>("RadiusM");

                            b1.Property<double?>("StructureHeightM");

                            b1.HasKey("FlightPlanEntityId");

                            b1.ToTable("FlightPlans");

                            b1.ToJson("PoiParameters");

                            b1.WithOwner()
                                .HasForeignKey("FlightPlanEntityId");
                        });

                    b.OwnsMany("DroneMesh3D.Core.FlightPath.Waypoint", "Waypoints", b1 =>
                        {
                            b1.Property<Guid>("FlightPlanEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("AltitudeAglM");

                            b1.Property<double>("GimbalPitchDegrees");

                            b1.Property<double>("GimbalYawDegrees");

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.HasKey("FlightPlanEntityId", "__synthesizedOrdinal");

                            b1.ToTable("FlightPlans");

                            b1.ToJson("Waypoints");

                            b1.WithOwner()
                                .HasForeignKey("FlightPlanEntityId");
                        });

                    b.Navigation("Area");

                    b.Navigation("GridParameters");

                    b.Navigation("PoiParameters");

                    b.Navigation("Waypoints");
                });
#pragma warning restore 612, 618
        }
    }
}
